project:
  type: website
  output-dir: docs

website:
  title: "ELD CAMA"
  open-graph: true
  navbar:
    background: dark
    search: true
    right:
        - icon: github
          href: "https://github.com/trustIndex-togge/eld"
        - text: "Home"
          file: index.qmd
        - sidebar:About
        - sidebar:Apps
  sidebar:
    - id: About
      title: Information
      style: docked
      background: dark
      contents: 
        - about.qmd
        - documentation.qmd
    - id: Apps
      title: Apps
      background: dark
      contents:
        - text: "Frequentist Meta-Analysis"
          href: "http://194.47.110.51:3838/frequentist_meta/"
        - text: "Bayesian Meta-Analysis"
          href: "http://194.47.110.51:3838/bayesian_meta/"
        - text: "Data Validation"
          href: "http://194.47.110.51:3838/data_validation/"
  page-footer:
    background: dark
    border: false
    left: "Attribution 4.0 International (CC BY 4.0)"
    right: "[Linnaeus University](https://lnu.se/) and [Linköping University](https://liu.se/en)"

format:
  html:
    smooth-scroll: true
    theme: 
      light: cosmo
      dark: cosmo
    css: styles.css
    toc: true

editor: visual

